### ISSUE TITLE
bug: MPRIS clients not properly displaying current playback status

### ISSUE THREAD

**Issue by talwat** [talwat/lowfi#37]
> Hi. I'm not sure if my thing is related or should be its own isue - $SUBJECT but for the MPRIS indicator.
> That one always displays a "play" button even if clicking it cycles between playing and not playing state.

**Comment by talwat** [comment]
I've gone ahead and implemented `PropertiesChanged` with https://github.com/talwat/lowfi/commit/978dfbc5e2f006c84ce27eb27ff365822b81a930, so if you could [test it](https://github.com/talwat/lowfi?tab=readme-ov-file#manual) then it'd be super helpful, since I don't have a GUI MPRIS client at the moment.

**Comment by Nindaleth** [comment]
Hey, that was very fast, thanks! 978dfbc is almost correct - the toggling between play and pause works with the proper icons displayed, but the initial state is incorrect.

I could see the indicator updating like this:
1. start `lowfi` - the indicator shows "unknown title" and ⏵ button (don't have the right answer here, could be ⏸ since autoplay is intended, could be ⏵ since nothing plays yet)
2. a track is fetched and starts playing - the indicator shows the name of the played track (always from now on) and ⏵ button (should definitely be ⏸ here)
3. pause the playback in any way - the indicator shows ⏵ button
4. resume the playback in any way - the indicator shows ⏸ button

Repeating steps 3 and 4 works as expected.

**Comment by Nindaleth** [comment]
For the record, this is how it now looks in GNOME (the disabled ⏮ in accordance with the project goals is a nice touch):
![mpris_indicator](https://github.com/user-attachments/assets/733545b4-56c2-4f30-831a-4ff338100ab4)

**Comment by talwat** [comment]
I've tried to fix number 2 with https://github.com/talwat/lowfi/commit/083d6c473c7c666d981f0f7f9ffec8f7ee61169a, and I think number 1 is client-specific since it's sending `PlaybackStatus::Stopped` which GNOME just _interprets_ that as ⏵.

The disabled ⏮ is actually a GNOME thing, since the library I'm using lets you specify which features your player supports and which aren't supported, so that's a neat little feature.

**Comment by Nindaleth** [comment]
Tried with 083d6c4 now, the initial icon state is now fixed :+1: There's one little remaining issue when skipping songs:

0. A song is playing
1. Pause the playback (⏵ is now shown)
2. Skip to the next song. This keeps the playback paused but changes the indicator to ⏸ (should have stayed ⏵)
3. Click the ⏸. That resumes the playback (⏸ is still shown which is correct at this point), further clicks cycle the play/pause icons as expected

**Comment by Nindaleth** [comment]
04d5ed3 fixes all the MPRIS indicator issues I could see in my tests :+1: I appreciate the speedy iterations.

**Comment by talwat** [comment]
Alright, with https://github.com/talwat/lowfi/commit/fe9429bfb3d81329164d94a6fb4d513a11894a85 I've cleaned up the MPRIS code a bit more, so just let me know when you've tested it and then I'll go ahead and publish the next version :)

**Comment by Nindaleth** [comment]
Tested fe9429b for a bit and everything seems to work as expected. Thanks for fixing this so quickly!

**Comment by talwat** [comment]
Alright! I'll make the next release later today with these changes.
