### ISSUE TITLE
`--track` shorthand for `~/.local/share/lowfi` doesn't work

### ISSUE THREAD

**Issue by danielwerg** [talwat/lowfi#39]
lowfi 1.5.2

While 

```sh
lowfi --tracks ~/.local/share/lowfi/micropop.txt
```

works just fine,

```sh
lowfi --tracks micropop
```

returns:

```
Error: No such file or directory (os error 2)

Location:
    src/tracks/list.rs:84:17
 ```
 
 ---
 
 Also to note, I'm using `lowfi` package from AUR and it didn't created `~/.local/share/lowfi` folder so I had to do that manually and populate it with data from https://github.com/talwat/lowfi/tree/main/data

**Comment by talwat** [comment]
Fixed with https://github.com/talwat/lowfi/commit/b12a7077a856e20e1917714fa47fab8c74708d87, let me know if it works now.

Also, about lowfi not creating it, that's intentional, since I only expected a handful of users to actually care about custom tracklists. This is in contrast to persistent volume, which a majority of users will probably find useful.

**Comment by danielwerg** [comment]
Works as expected now! Thanks for quick fix :)
